service: bookmark-chrome-extension
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  environment:
    variable1: value1

custom:
  serverless-offline:
    port: 4000

functions:
  getBookmarks:
    name: '${self:service}-get-bookmarks'
    handler: src/routes/get-bookmarks.handler
    events:
      - http:
          path: bookmarks
          method: get
