service: bookmark-chrome-extension
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

custom:
  serverless-offline:
    port: 4000

functions:
  getBookmarks:
    name: '${self:service}-get-bookmarks'
    handler: src/routes/get-bookmarks.handler
    events:
      - http:
          path: bookmarks
          method: get

  createBookmarks:
    name: '${self:service}-create-bookmark'
    handler: src/routes/create-bookmark.handler
    events:
      - http:
          path: bookmarks
          method: post

  updateBookmarks:
    name: '${self:service}-update-bookmark'
    handler: src/routes/update-bookmark.handler
    events:
      - http:
          path: bookmarks
          method: put
