service: bookmark-chrome-extension
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  environment:
    DB_URL: ${file(.secret.yml):DB_URL}

custom:
  serverless-offline:
    port: 4000

functions:
  getBookmarks:
    name: '${self:service}-get-bookmarks'
    handler: src/routes/bookmarks/get-bookmarks.handler
    events:
      - http:
          path: bookmarks
          method: get

  updateBookmarks:
    name: '${self:service}-update-bookmark'
    handler: src/routes/bookmarks/update-bookmark.handler
    events:
      - http:
          path: bookmarks/{id}
          method: put

  deleteBookmarks:
    name: '${self:service}-delete-bookmark'
    handler: src/routes/bookmarks/delete-bookmark.handler
    events:
      - http:
          path: bookmarks/{id}
          method: delete

  getGroupsWithBookmarks:
    name: '${self:service}-get-groups'
    handler: src/routes/groups/get-groups.handler
    events:
      - http:
          path: groups
          method: get

  createGroup:
    name: '${self:service}-create-group'
    handler: src/routes/groups/create-group.handler
    events:
      - http:
          path: groups
          method: post

  updateBookmark:
    name: '${self:service}-update-group'
    handler: src/routes/groups/update-group.handler
    events:
      - http:
          path: groups/{id}
          method: put

  deleteGroup:
    name: '${self:service}-delete-group'
    handler: src/routes/groups/delete-group.handler
    events:
      - http:
          path: groups/{id}
          method: delete
